// Auto-generated by fix_and_verify.sh -- ESSource ProductResolver registrations
// for the Phase-2 ECAL multifit condition records, so PoolDBESSource can READ them.
// In src/ (globbed into the EDM_PLUGIN library by the package root BuildFile), NOT
// plugins/ (which lists PayloadInspector files by name and would never compile this).
// CATIA => NO_SERIAL: its payload EcalCondObjectContainer<float> is already
// serial-registered upstream (EcalIntercalibConstantsRcd).
#include "CondCore/ESSources/interface/registration_macros.h"

#include "CondFormats/DataRecord/interface/EcalLiteDTUPedestalsRcd.h"
#include "CondFormats/EcalObjects/interface/EcalLiteDTUPedestals.h"
#include "CondFormats/DataRecord/interface/EcalCATIAGainRatiosRcd.h"
#include "CondFormats/EcalObjects/interface/EcalCATIAGainRatios.h"
#include "CondFormats/DataRecord/interface/EcalPh2PulseShapesRcd.h"
#include "CondFormats/EcalObjects/interface/EcalPulseShapeT.h"
#include "CondFormats/DataRecord/interface/EcalPh2PulseCovariancesRcd.h"
#include "CondFormats/EcalObjects/interface/EcalPulseCovarianceT.h"

REGISTER_PLUGIN(EcalLiteDTUPedestalsRcd, EcalLiteDTUPedestalsMap);
REGISTER_PLUGIN_NO_SERIAL(EcalCATIAGainRatiosRcd, EcalCATIAGainRatios);
REGISTER_PLUGIN(EcalPh2PulseShapesRcd, EcalPh2PulseShapes);
REGISTER_PLUGIN(EcalPh2PulseCovariancesRcd, EcalPh2PulseCovariances);
